Repository rubyforgood/human-essentials, pull requests merged in 2019-06, with the labels that each got.

#1048 Update README with "diaper_dev" as db name
  README.md
Labels: Repo First-timer

#1044 adds the SimpleCov gem to the project
  .gitignore
  Gemfile
  Gemfile.lock
  spec/spec_helper.rb
Labels: Repo First-timer

#1047 Add tests for Admin::OrganizationsController
  spec/controllers/admin/organizations_controller_spec.rb
Labels: Repo First-timer

#1030 Incorrect diaper drive numbers
  app/helpers/dashboard_helper.rb
  app/models/donation.rb
  app/views/dashboard/index.html.erb
  spec/controllers/donations_controller_spec.rb
  spec/controllers/purchases_controller_spec.rb
  spec/factories/adjustments.rb
  spec/factories/audits.rb
  spec/factories/donations.rb
  spec/factories/line_items.rb
  spec/factories/manufacturers.rb
  spec/factories/purchases.rb
  spec/factories/transfers.rb
  spec/models/distribution_spec.rb
  spec/models/donation_spec.rb
  spec/models/item_spec.rb
  spec/models/line_item_spec.rb
  spec/models/purchase_spec.rb
  spec/support/itemizable_shared_example.rb
  spec/system/dashboard_system_spec.rb
  spec/system/donation_system_spec.rb
Labels: In Progress

#1009 Storage Location count issue
  app/controllers/storage_locations_controller.rb
  app/models/adjustment.rb
  app/models/purchase.rb
  app/queries/items_in_query.rb
  app/queries/items_in_total_query.rb
  app/queries/items_out_query.rb
  app/queries/items_out_total_query.rb
  app/views/storage_locations/_line_item_row.html.erb
  app/views/storage_locations/show.html.erb
  spec/factories/donations.rb
  spec/factories/purchases.rb
  spec/factories/transfers.rb
  spec/features/item_spec.rb
  spec/models/adjustment_spec.rb
  spec/models/donation_spec.rb
  spec/models/purchase_spec.rb
  spec/queries/items_in_query_spec.rb
  spec/queries/items_in_total_query_spec.rb
  spec/queries/items_out_query_spec.rb
  spec/queries/items_out_total_query_spec.rb
  spec/system/dashboard_system_spec.rb
  spec/system/item_system_spec.rb
  spec/system/storage_location_system_spec.rb
Labels: In Progress

#1007 Remove quantity items on audit #990
  app/assets/javascripts/distributions_and_transfers.coffee
  spec/features/audit_spec.rb
Labels: In Progress, Repo First-timer

#1069 Fix Distribution Show Page
  app/views/distributions/_distribution_item_row.html.erb
  app/views/distributions/show.html.erb
  spec/features/distribution_spec.rb
Labels: Repo First-timer

#1059 #1042 - Show devise flash error on sign_in page
  app/views/devise/sessions/new.html.erb
  app/views/layouts/application.html.erb
  app/views/shared/_flash.html.erb
  spec/features/sign_in_spec.rb
Labels: Repo First-timer
