Repository rubyforgood/human-essentials, pull requests merged in 2019-05, with the labels that each got.

#929 [Issue-853] WIP - Updating user index view to boostrap 4
  app/views/users/index.html.erb
Labels: RAILSCONF

#931 [837] Updating the donations/index page theme
  app/views/donations/index.html.erb
Labels: RAILSCONF

#928 Update Diaper Drive Participant Show to use new theme
  app/views/diaper_drive_participants/show.html.erb
Labels: RAILSCONF

#924 Resolve #844 - Update Organizations Index to Use New Theme
  README.md
  app/views/admin/organizations/index.html.erb
  spec/rails_helper.rb
  spec/system/account_system_spec.rb
  spec/system/adjustment_system_spec.rb
Labels: RAILSCONF

#916 Update Audits Index to Use New Theme
  app/views/audits/index.html.erb
Labels: RAILSCONF

#932 Convert admin/feedback Feature spec to System spec
  spec/system/admin/feedback_system_spec.rb
Labels: RAILSCONF

#936 [WIP] convert donation feature spec to system spec
  spec/system/donation_system_spec.rb
Labels: RAILSCONF

#934 update admin users feature spec to system spec
  spec/system/users_system_spec.rb
Labels: RAILSCONF

#917 Update admin-organization-new page to new template
  app/views/admin/organizations/_form.html.erb
  app/views/admin/organizations/new.html.erb
Labels: RAILSCONF

#912 828 Update barcode item feature spec to system spec
  spec/system/barcode_item_system_spec.rb
Labels: RAILSCONF

#914 added a log in system spec, original log in feature spec is still there
  spec/system/log_in_system_spec.rb
Labels: RAILSCONF

#926 adds new dashboard system spec to move to the new standards
  spec/system/dashboard_system_spec.rb
Labels: RAILSCONF

#921 issue 908 - update storage-location edit view for new theme
  app/views/storage_locations/edit.html.erb
Labels: RAILSCONF, Repo First-timer

#942 888 Update vendor feature spec to system spec
  spec/system/vendor_system_spec.rb
Labels: RAILSCONF

#925 Theme update for "Distributions New"
  app/views/distributions/new.html.erb
  app/views/line_items/_line_item_fields.html.erb
Labels: RAILSCONF, Repo First-timer

#939 Issue #834 - Update Adjustments Index to Use New Theme
  app/views/adjustments/index.html.erb
Labels: RAILSCONF, Repo First-timer

#927 WIP - Issue #854 - Update Views Index to new bootstrap theme
  .env.example
  README.md
  app/views/vendors/index.html.erb
Labels: RAILSCONF, Repo First-timer

#922 Issue #855 - Update adjustment new page to use bootstrap 4 theme
  app/views/adjustments/new.html.erb
Labels: RAILSCONF, Repo First-timer

#923 fixes #840 - Update DiaperDriveParticipants#index to use new bootstrap theme
  app/views/diaper_drive_participants/index.html.erb
Labels: RAILSCONF, Repo First-timer

#930 [#860] updated diaper drive participant new theme + feature specs
  app/views/diaper_drive_participants/new.html.erb
  spec/features/diaper_drive_participant_spec.rb
Labels: RAILSCONF, Repo First-timer

#919 Resolves #825 Update audit feature spec to system spec
  spec/features/audit_spec.rb
  spec/system/audit_system_spec.rb
Labels: RAILSCONF, Repo First-timer

#933 Issue #836 - Update BarCodeItems#index to use new theme
  app/views/barcode_items/index.html.erb
  yarn.lock
Labels: RAILSCONF, Repo First-timer

#935 change sections to divs as per bootstrap 4 in rails-conf workshop
  app/views/donation_sites/index.html.erb
Labels: RAILSCONF, Repo First-timer

#718 Fixes #473 Refactor inventory changing methods mkd/amh
  Gemfile
  Gemfile.lock
  app/controllers/adjustments_controller.rb
  app/controllers/audits_controller.rb
  app/controllers/distributions_controller.rb
  app/controllers/donations_controller.rb
  app/controllers/purchases_controller.rb
  app/controllers/transfers_controller.rb
  app/models/adjustment.rb
  app/models/concerns/itemizable.rb
  app/models/distribution.rb
  app/models/donation.rb
  app/models/item.rb
  app/models/purchase.rb
  app/models/storage_location.rb
  app/views/distributions/_distribution_row.html.erb
  config/routes.rb
  spec/controllers/donations_controller_spec.rb
  spec/controllers/purchases_controller_spec.rb
  spec/factories/adjustments.rb
  spec/features/adjustment_spec.rb
  spec/features/distribution_spec.rb
  spec/features/item_spec.rb
  spec/models/adjustment_spec.rb
  spec/models/distribution_spec.rb
  spec/models/donation_spec.rb
  spec/models/item_spec.rb
  spec/models/purchase_spec.rb
  spec/models/storage_location_spec.rb
  spec/support/itemizable_shared_example.rb
  spec/system/adjustment_system_spec.rb
  spec/system/transfer_system_spec.rb
Labels: CRITICAL

#813 Added the cancel button
  app/controllers/requests_controller.rb
  app/views/requests/_request_row.html.erb
  app/views/requests/index.html.erb
  app/views/requests/show.html.erb
  config/routes.rb
  spec/controllers/requests_controller_spec.rb
Labels: Github First-timer, Loyola

#1017 Resolve Upstream Conflicts with Loyno-Request Delete feature
  app/controllers/requests_controller.rb
  app/views/requests/_request_row.html.erb
  app/views/requests/index.html.erb
  app/views/requests/show.html.erb
  config/routes.rb
  spec/controllers/requests_controller_spec.rb
  spec/features/distribution_spec.rb
  spec/system/request_system_spec.rb
Labels: In Progress

#1014 #955 Add barcode "boop" test helper.
  spec/features/distribution_spec.rb
  spec/support/barcode_helper.rb
  spec/system/donation_system_spec.rb
  spec/system/purchase_system_spec.rb
Labels: Repo First-timer

#1013 821 Create manufacturers on new donations
  app/assets/javascripts/donations.coffee.erb
  app/controllers/dashboard_controller.rb
  app/controllers/donations_controller.rb
  app/controllers/manufacturers_controller.rb
  app/models/donation.rb
  app/models/manufacturer.rb
  app/models/organization.rb
  app/views/dashboard/_manufacturer.html.erb
  app/views/dashboard/index.html.erb
  app/views/donations/_donation_form.html.erb
  app/views/donations/index.html.erb
  app/views/donations/new.html.erb
  app/views/layouts/_lte_sidebar.html.erb
  app/views/manufacturers/_form.html.erb
  app/views/manufacturers/_manufacturer_row.html.erb
  app/views/manufacturers/_new_modal.html.erb
  app/views/manufacturers/create.js.erb
  app/views/manufacturers/edit.html.erb
  app/views/manufacturers/index.html.erb
  app/views/manufacturers/new.html.erb
  app/views/manufacturers/new_modal.js.erb
  app/views/manufacturers/show.html.erb
  config/routes.rb
  db/migrate/20190520022544_create_manufacturers.rb
  db/migrate/20190520033128_add_manufacturer_to_donation.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/donations.rb
  spec/factories/manufacturer.rb
  spec/models/donation_spec.rb
  spec/models/manufacturer_spec.rb
  spec/system/dashboard_system_spec.rb
  spec/system/donation_system_spec.rb
  spec/system/manufacturer_system_spec.rb
Labels: Repo First-timer

#1006 Update organizations/edit.html.erb to use new theme
  app/views/organizations/_form.html.erb
  app/views/organizations/edit.html.erb
Labels: RAILSCONF
