Repository rubyforgood/human-essentials, pull requests merged in 2019-10, with the labels that each got.

#1256 Auto submit on the checkbox filter
  app/assets/javascripts/dashboard.js
  app/views/items/_header.html.erb
Labels: Repo First-timer

#1250 [1246] Guard against running seeds.rb in production mode. (#1246)
  db/seeds.rb
Labels: Repo First-timer, hacktoberfest

#1224 #1199 improve action language
  .gitignore
  app/views/admin/barcode_items/index.html.erb
  app/views/admin/base_items/index.html.erb
  app/views/admin/users/index.html.erb
  app/views/audits/index.html.erb
  app/views/barcode_items/index.html.erb
  app/views/dashboard/index.html.erb
  app/views/diaper_drive_participants/index.html.erb
  app/views/distributions/index.html.erb
  app/views/donation_sites/index.html.erb
  app/views/donations/index.html.erb
  app/views/items/_header.html.erb
  app/views/items/_item_list.html.erb
  app/views/manufacturers/index.html.erb
  app/views/partners/index.html.erb
  app/views/purchases/index.html.erb
  app/views/requests/index.html.erb
  app/views/storage_locations/index.html.erb
  app/views/vendors/index.html.erb
Labels: Repo First-timer

#1227 [1219] Assign a one dollar value to random items in seeds
  db/seeds.rb
Labels: Repo First-timer

#1247 1189 | when creating new org as site admin, do not require PW
  app/controllers/admin/organizations_controller.rb
  app/views/admin/users/_user_form_fields.html.erb
  spec/controllers/admin/organizations_controller_spec.rb
  spec/system/admin/organizations_system_spec.rb
Labels: Repo First-timer, hacktoberfest

#1249 [1239] Adds user association to Adjustment
  app/controllers/adjustments_controller.rb
  app/controllers/audits_controller.rb
  app/models/adjustment.rb
  app/models/organization.rb
  app/models/storage_location.rb
  db/migrate/20191002232744_add_user_id_to_adjustments.rb
  db/schema.rb
  db/seeds.rb
  spec/controllers/adjustments_controller_spec.rb
  spec/factories/adjustments.rb
  spec/factories/organizations.rb
  spec/models/adjustment_spec.rb
  spec/models/storage_location_spec.rb
Labels: hacktoberfest

#1254 Add Kaminari and first implementation of pagination
  Gemfile
  Gemfile.lock
  app/controllers/donations_controller.rb
  app/views/donations/index.html.erb
  app/views/kaminari/_first_page.html.erb
  app/views/kaminari/_gap.html.erb
  app/views/kaminari/_last_page.html.erb
  app/views/kaminari/_next_page.html.erb
  app/views/kaminari/_page.html.erb
  app/views/kaminari/_paginator.html.erb
  app/views/kaminari/_prev_page.html.erb
  config/initializers/kaminari_config.rb
  spec/system/donation_system_spec.rb
Labels: hacktoberfest

#1259 Display Donation View fields in tabular form
  app/assets/stylesheets/AdminLTE.scss
  app/views/donations/show.html.erb
Labels: Repo First-timer, hacktoberfest

#1273 Adds pagination to items
  app/controllers/items_controller.rb
  app/views/items/_item_list.html.erb
Labels: hacktoberfest

#1274 1240 - Add filter-by User on Adjustments#index
  app/controllers/adjustments_controller.rb
  app/models/adjustment.rb
  app/views/adjustments/index.html.erb
  spec/features/adjustment_spec.rb
  spec/models/adjustment_spec.rb
  spec/system/adjustment_system_spec.rb
Labels: hacktoberfest

#1271 Adds pagination to the requests index page
  app/controllers/requests_controller.rb
  app/views/requests/index.html.erb
Labels: hacktoberfest

#1269 Adds pagination to the distributions index page
  app/controllers/distributions_controller.rb
  app/views/distributions/_distribution_total.html.erb
  app/views/distributions/index.html.erb
Labels: Repo First-timer, hacktoberfest

#1262 split form into 2 columns, cleanup indentation.
  app/views/devise/registrations/edit.html.erb
Labels: Repo First-timer, hacktoberfest

#1261 Add button to download a barcode font
  app/controllers/barcode_items_controller.rb
  app/views/barcode_items/index.html.erb
  config/routes.rb
  public/fonts/LibreBarcode128-Regular.ttf
Labels: Repo First-timer, hacktoberfest

#1272 Adds pagination to inventory adjustments
  app/controllers/adjustments_controller.rb
  app/views/adjustments/index.html.erb
Labels: Repo First-timer, hacktoberfest

#1275 Ftr/reminder distributions 1134
  app/controllers/distributions_controller.rb
  app/jobs/distribution_reminder_job.rb
  app/mailers/distribution_mailer.rb
  app/views/distribution_mailer/reminder_email.html.erb
  app/views/distributions/edit.html.erb
  config/initializers/sidekiq.rb
  db/migrate/20190917235330_add_reminder_email_enabled_to_distributions.rb
  db/schema.rb
  spec/jobs/distribution_reminder_mailer_job_spec.rb
Labels: hacktoberfest

#1255 [1231] WIP: Add a control for org admins to promote other users to be org admins too
  app/controllers/organizations_controller.rb
  app/helpers/ui_helper.rb
  app/views/admin/organizations/show.html.erb
  app/views/organizations/show.html.erb
  app/views/users/_organization_user.html.erb
  config/routes.rb
  spec/controllers/organizations_controller_spec.rb
Labels: Repo First-timer, hacktoberfest

#1280 Be able to manage "Partner" data in the SiteAdmin dashboard
  app/controllers/admin/partners_controller.rb
  app/views/admin/partners/edit.html.erb
  app/views/admin/partners/index.html.erb
  app/views/admin/partners/show.html.erb
  app/views/layouts/_lte_admin_sidebar.html.erb
  config/routes.rb
  spec/controllers/admin/partners_controller_spec.rb
Labels: Repo First-timer, hacktoberfest

#1284 HOTFIX distribution insufficient quantity bug
  app/controllers/distributions_controller.rb
  app/helpers/application_helper.rb
  app/models/errors.rb
  app/views/shared/_flash.html.erb
  spec/controllers/distributions_controller_spec.rb
  spec/controllers/donations_controller_spec.rb
  spec/controllers/purchases_controller_spec.rb
  spec/helpers/application_helper_spec.rb
  spec/system/distribution_system_spec.rb
Labels: hacktoberfest

#1263 Fix table columns alignment for numerals and dates
  app/assets/stylesheets/application.scss
  app/views/adjustments/index.html.erb
  app/views/adjustments/show.html.erb
  app/views/admin/barcode_items/_barcode_item_row.html.erb
  app/views/admin/barcode_items/index.html.erb
  app/views/admin/organizations/_organization_row.html.erb
  app/views/admin/organizations/index.html.erb
  app/views/audits/index.html.erb
  app/views/barcode_items/_barcode_item_row.html.erb
  app/views/barcode_items/index.html.erb
  app/views/diaper_drive_participants/_diaper_drive_participant_row.html.erb
  app/views/diaper_drive_participants/index.html.erb
  app/views/diaper_drive_participants/show.html.erb
  app/views/distributions/_distribution_item_row.html.erb
  app/views/distributions/_distribution_item_total.html.erb
  app/views/distributions/_distribution_row.html.erb
  app/views/distributions/index.html.erb
  app/views/distributions/show.html.erb
  app/views/donation_sites/show.html.erb
  app/views/donations/_donation_item_row.html.erb
  app/views/donations/_donation_row.html.erb
  app/views/donations/index.html.erb
  app/views/donations/show.html.erb
  app/views/items/_item_list.html.erb
  app/views/items/_item_row.html.erb
  app/views/items/_item_row_quantity_and_storages.html.erb
  app/views/items/_items_quantity_and_location.html.erb
  app/views/items/_storage_column.html.erb
  app/views/items/show.html.erb
  app/views/manufacturers/_manufacturer_row.html.erb
  app/views/manufacturers/index.html.erb
  app/views/manufacturers/show.html.erb
  app/views/partners/show.html.erb
  app/views/purchases/_purchase_item_row.html.erb
  app/views/purchases/_purchase_row.html.erb
  app/views/purchases/index.html.erb
  app/views/purchases/show.html.erb
  app/views/requests/_request_row.html.erb
  app/views/requests/index.html.erb
  app/views/requests/show.html.erb
  app/views/storage_locations/_inventory_item_row.html.erb
  app/views/storage_locations/_line_item_row.html.erb
  app/views/storage_locations/_storage_location_row.html.erb
  app/views/storage_locations/index.html.erb
  app/views/storage_locations/show.html.erb
  app/views/transfers/_transfer_row.html.erb
  app/views/transfers/index.html.erb
  app/views/transfers/show.html.erb
  app/views/vendors/_vendor_row.html.erb
  app/views/vendors/index.html.erb
  app/views/vendors/show.html.erb
Labels: Repo First-timer, hacktoberfest

#1279 1237 - Show total item value for each location
  app/models/storage_location.rb
  app/views/storage_locations/_storage_location_row.html.erb
  app/views/storage_locations/index.html.erb
  spec/models/storage_location_spec.rb
Labels: hacktoberfest

#1248 Datepicker component
  Gemfile
  app/assets/javascripts/application.js
  app/assets/stylesheets/application.scss
  app/helpers/dateable.rb
  app/views/donations/index.html.erb
  app/views/purchases/index.html.erb
  spec/system/purchase_system_spec.rb
Labels: hacktoberfest

#1258 add on hand minimum and recommended quantity to item
  app/controllers/items_controller.rb
  app/models/item.rb
  app/queries/items_by_storage_collection_and_quantity_query.rb
  app/queries/items_by_storage_collection_query.rb
  app/views/items/_form.html.erb
  app/views/items/_item_row_quantity_and_storages.html.erb
  app/views/items/_items_quantity_and_location.html.erb
  db/migrate/20190927193927_add_on_hand_minimum_and_on_hand_recommended_quantity_to_item.rb
  db/schema.rb
  spec/factories/items.rb
  spec/models/item_spec.rb
Labels: hacktoberfest

#1298 Add OS X setup instructions
  installation.md
Labels: Repo First-timer

#1293 Change seed to array
  db/seeds.rb
  spec/system/admin/barcode_items_system_spec.rb
Labels: hacktoberfest

#1300 fix(TestCoverage)[LB] Add failure test coverage for updating an admi…
  spec/controllers/admin/partners_controller_spec.rb
Labels: hacktoberfest

#1304 1302 distribution index summing
  app/controllers/distributions_controller.rb
  spec/controllers/distributions_controller_spec.rb
Labels: Repo First-timer, hacktoberfest

#1307 1181 upgrade rails 6
  Gemfile
  Gemfile.lock
  app/models/organization.rb
  bin/setup
  config/application.rb
  config/boot.rb
  config/cable.yml
  config/environments/development.rb
  config/environments/test.rb
  config/initializers/application_controller_renderer.rb
  config/initializers/content_security_policy.rb
  config/initializers/jbuilder.rb
  config/initializers/new_framework_defaults_5_2.rb
  config/locales/en.yml
  db/schema.rb
  spec/rails_helper.rb
Labels: hacktoberfest

#1257 add total inventory fair market value on views and tests
  app/models/storage_location.rb
  app/views/storage_locations/_storage_location_row.html.erb
  app/views/storage_locations/index.html.erb
  spec/models/storage_location_spec.rb
Labels: hacktoberfest

#1289 Add date filtering to Transfers#index
  app/controllers/transfers_controller.rb
  app/views/transfers/_transfer_row.html.erb
  app/views/transfers/index.html.erb
  spec/controllers/transfers_controller_spec.rb
  spec/system/transfer_system_spec.rb
Labels: Repo First-timer, hacktoberfest

#1290 Add date filtering to Adjustments#index
  app/controllers/adjustments_controller.rb
  app/views/adjustments/index.html.erb
  spec/controllers/adjustments_controller_spec.rb
  spec/system/adjustment_system_spec.rb
Labels: hacktoberfest
