Repository rubyforgood/human-essentials, pull requests merged in 2019-07, with the labels that each got.

#1108 1093 distribution filter
  app/models/distribution.rb
  spec/models/distribution_spec.rb
Labels: Repo First-timer, Ruby for Good

#1104 add purchased date column for purchase page
  app/views/purchases/_purchase_row.html.erb
  app/views/purchases/index.html.erb
  spec/system/purchase_system_spec.rb
Labels: Repo First-timer, Ruby for Good

#1121 Extracts Date range helpers to separate helpers file
  app/assets/javascripts/dashboard.coffee
  app/helpers/dashboard_helper.rb
  app/helpers/date_range_helper.rb
  app/views/dashboard/index.html.erb
  spec/system/dashboard_system_spec.rb
Labels: Ruby for Good

#1096 Barcode scanning feature
  app/assets/javascripts/application.js
  app/assets/javascripts/barcode_scan.js
  app/assets/stylesheets/distribution.scss
  app/views/admin/barcode_items/_form.html.erb
  app/views/admin/barcode_items/index.html.erb
  app/views/distributions/edit.html.erb
  app/views/donations/_barcode_modal.html.erb
  app/views/line_items/_line_item_fields.html.erb
  app/views/purchases/_barcode_modal.html.erb
  db/schema.rb
  spec/system/admin/barcode_items_system_spec.rb
  spec/system/donation_system_spec.rb
  spec/system/purchase_system_spec.rb
  vendor/assets/javascripts/quagga.js
Labels: Ruby for Good

#1118 Validate and confirm item quantity for large donations
  app/assets/javascripts/donations.coffee.erb
  app/assets/javascripts/inventories.coffee
  app/assets/javascripts/items.coffee
  app/assets/javascripts/landing.coffee
  app/assets/javascripts/partners.coffee
  app/assets/stylesheets/purchases.scss
  app/models/inventory_item.rb
  app/models/line_item.rb
  app/views/line_items/_line_item_fields.html.erb
  spec/models/inventory_item_spec.rb
  spec/models/line_item_spec.rb
  spec/system/donation_system_spec.rb
Labels: Repo First-timer

#1148 barcode styling fix
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/distribution.scss
  app/views/purchases/_barcode_modal.html.erb
Labels: Ruby For Good 2019

#1155 Removes CoffeeScript
  Gemfile
  Gemfile.lock
  app/assets/javascripts/adjustments.coffee
  app/assets/javascripts/adjustments.js
  app/assets/javascripts/application.js
  app/assets/javascripts/dashboard.coffee
  app/assets/javascripts/dashboard.js
  app/assets/javascripts/distributions_and_transfers.coffee
  app/assets/javascripts/distributions_and_transfers.js
  app/assets/javascripts/donations.coffee.erb
  app/assets/javascripts/donations.js.erb
  app/assets/javascripts/purchases.coffee.erb
  app/assets/javascripts/purchases.js.erb
Labels: Repo First-timer

#1157 1107 I made the donation site field required
  app/views/donations/_donation_form.html.erb
Labels: Ruby For Good 2019

#1150 Switch nested fields to simple_form
  app/views/line_items/_line_item_fields.html.erb
  spec/system/donation_system_spec.rb
  spec/system/purchase_system_spec.rb
Labels: Ruby For Good 2019

#1153 Fixed the total distributions bug
  app/controllers/distributions_controller.rb
  app/views/distributions/_distribution_total.html.erb
Labels: Ruby For Good 2019

#1163 Add filtering by date range to distribution resource
  app/controllers/distributions_controller.rb
  app/helpers/date_range_helper.rb
  app/views/distributions/index.html.erb
  spec/models/distribution_spec.rb
  spec/system/distribution_system_spec.rb
Labels: Ruby For Good 2019, Ruby for Good

#1160 1100 add active filter to items
  app/controllers/items_controller.rb
  app/queries/items_by_storage_collection_and_quantity_query.rb
  app/queries/items_by_storage_collection_query.rb
  app/views/items/_header.html.erb
  spec/system/item_system_spec.rb
Labels: Ruby For Good 2019, Ruby for Good

#1161 Item Type Page Cleanup
  app/controllers/items_controller.rb
  app/views/items/_item_list.html.erb
  app/views/items/_item_row.html.erb
  app/views/items/_item_row_quantity.html.erb
  app/views/items/_item_row_quantity_and_storages.html.erb
  app/views/items/_items_and_quantity.html.erb
  app/views/items/_items_quantity_and_location.html.erb
  app/views/items/index.html.erb
  spec/features/item_spec.rb
  spec/system/item_system_spec.rb
Labels: BLOCKED, Ruby For Good 2019, Ruby for Good
