Repository rubyforgood/human-essentials, pull requests merged in 2020-09, with the labels that each got.

#1811 Allow admins to deactivate and reactivate organization users
  Gemfile
  Gemfile.lock
  app/controllers/organizations_controller.rb
  app/helpers/ui_helper.rb
  app/models/user.rb
  app/views/organizations/show.html.erb
  app/views/users/_organization_user.html.erb
  config/routes.rb
  db/migrate/20200905145818_add_discarded_at_to_users.rb
  db/migrate/20200905204920_add_discarded_at_index_to_users.rb
  db/schema.rb
  spec/controllers/organizations_controller_spec.rb
  spec/factories/users.rb
  spec/models/user_spec.rb
  spec/system/log_in_system_spec.rb
  spec/system/organization_system_spec.rb
Labels: Ruby For Good 🎃 Fall 2020

#1813 Adding "Make User" button to demote admins to users
  app/controllers/organizations_controller.rb
  app/views/users/_organization_user.html.erb
  config/routes.rb
  spec/controllers/organizations_controller_spec.rb
  spec/system/organization_system_spec.rb
Labels: Ruby For Good 🎃 Fall 2020

#1816 Add Item Visibility
  app/controllers/items_controller.rb
  app/models/item.rb
  app/models/organization.rb
  app/views/items/_form.html.erb
  db/migrate/20200906155253_add_visible_to_partners_to_items.rb
  db/schema.rb
  spec/controllers/items_controller_spec.rb
  spec/factories/items.rb
  spec/models/item_spec.rb
  spec/models/organization_spec.rb
  spec/requests/api/v1/api_v1_partner_requests_spec.rb
  spec/system/item_system_spec.rb
Labels: Repo First-timer, Ruby For Good 🎃 Fall 2020

#1808 Fixes extra line item appearing in distribution form for edit and edit with errors
  app/controllers/distributions_controller.rb
  spec/system/distribution_system_spec.rb
Labels: Ruby For Good 🎃 Fall 2020

#1831 1804 feedback sort
  app/views/admin/feedback_messages/index.html.erb
  spec/system/admin/feedback_system_spec.rb
Labels: Repo First-timer, Ruby For Good 🎃 Fall 2020, ❇️ Github First-timer

#1812 Refactor donation source text
  app/models/diaper_drive.rb
  app/models/diaper_drive_participant.rb
  app/models/donation.rb
  spec/models/diaper_drive_participant_spec.rb
  spec/models/diaper_drive_spec.rb
  spec/models/donation_spec.rb
Labels: Repo First-timer, Ruby For Good 🎃 Fall 2020

#1836 Remove the X from dashboard cards
  app/views/dashboard/index.html.erb
Labels: Ruby For Good 🎃 Fall 2020

#1835 Enqueue PartnerMailerJob into sidekiq default queue
  app/controllers/distributions_controller.rb
  app/jobs/partner_mailer_job.rb
  app/services/distribution_create_service.rb
  spec/jobs/partner_mailer_job_spec.rb
  spec/requests/distributions_requests_spec.rb
  spec/services/distribution_create_service_spec.rb
  spec/system/distribution_system_spec.rb
Labels: Ruby For Good 🎃 Fall 2020

#1822 Refactor transfer quantity validation
  app/models/line_item.rb
  app/models/storage_location.rb
  app/models/transfer.rb
Labels: Ruby For Good 🎃 Fall 2020

#1833 Provide low inventory notifications when distributions are created or updated
  app/controllers/distributions_controller.rb
  app/models/inventory_item.rb
  app/models/item.rb
  app/services/inventory_check_service.rb
  spec/controllers/distributions_controller_spec.rb
  spec/services/inventory_check_service_spec.rb
  spec/system/distribution_system_spec.rb
Labels: Ruby For Good 🎃 Fall 2020

#1818 Add "Pick up" vs "Delivery" for Distributions
  app/controllers/distributions_controller.rb
  app/models/distribution.rb
  app/services/distribution_update_service.rb
  app/views/distribution_mailer/partner_mailer.html.erb
  app/views/distribution_mailer/reminder_email.html.erb
  app/views/distributions/_distribution_row.html.erb
  app/views/distributions/_pickup_day_row.html.erb
  app/views/distributions/edit.html.erb
  app/views/distributions/index.html.erb
  app/views/distributions/new.html.erb
  app/views/distributions/pick_ups.html.erb
  app/views/distributions/pickup_day.html.erb
  app/views/distributions/show.html.erb
  app/views/layouts/_lte_sidebar.html.erb
  config/initializers/simple_form_bootstrap.rb
  db/migrate/20200906185544_add_delivery_method_to_distribution.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/distributions.rb
  spec/mailers/distribution_mailer_spec.rb
  spec/models/distribution_spec.rb
  spec/requests/distributions_requests_spec.rb
  spec/services/distribution_create_service_spec.rb
  spec/services/distribution_update_service_spec.rb
  spec/system/distribution_system_spec.rb
  spec/system/request_system_spec.rb
Labels: Repo First-timer, Ruby For Good 🎃 Fall 2020

#1867 feature/add-distributions-status-filtering
  app/controllers/distributions_controller.rb
  app/models/distribution.rb
  app/views/distributions/index.html.erb
  spec/system/distribution_system_spec.rb
Labels: ⚡️ Power ⚡️

#1889 1852 Feature/calculate product totals
  app/controllers/requests_controller.rb
  app/views/requests/_calculate_product_totals.html.erb
  app/views/requests/index.html.erb
Labels: ⚡️ Power ⚡️

#1891 Add filters to requests page
  app/controllers/requests_controller.rb
  app/models/request.rb
  app/views/requests/index.html.erb
  spec/system/request_system_spec.rb
Labels: ⚡️ Power ⚡️

#1910 Display inventory number based off storage location
  app/assets/javascripts/distributions_and_transfers.js
  app/views/distributions/new.html.erb
Labels: ⚡️ Power ⚡️

#1894 1855 Add forecasting for distributions
  app/assets/javascripts/application.js
  app/controllers/forecasting/base_controller.rb
  app/controllers/forecasting/distributions_controller.rb
  app/controllers/forecasting/donations_controller.rb
  app/controllers/forecasting/purchases_controller.rb
  app/helpers/application_helper.rb
  app/views/forecasting/distributions/index.html.erb
  app/views/forecasting/donations/index.html.erb
  app/views/forecasting/purchases/index.html.erb
  app/views/layouts/_lte_sidebar.html.erb
  app/views/shared/_highcharts.html.erb
  config/routes.rb
  package.json
  spec/helpers/application_helper_spec.rb
  yarn.lock
Labels: ⚡️ Power ⚡️
