Repository rubyforgood/human-essentials, pull requests merged in 2020-10, with the labels that each got.

#1950 updated "Items removed" to "Items Removed" text
  app/views/distribution_mailer/_distribution_changes.html.erb
Labels: Repo First-timer

#1947 BUGFIX: Pre-loads items collection, alphabetized, and scopes to organization
  app/controllers/kits_controller.rb
  app/views/kits/index.html.erb
Labels: hacktoberfest

#1949 Persist filter choices in requests and distributions
  app/controllers/distributions_controller.rb
  app/controllers/requests_controller.rb
  app/views/distributions/index.html.erb
  app/views/requests/index.html.erb
Labels: hacktoberfest

#1962 Prevent raising NotFound error if bad item_id is specified
  app/controllers/requests_controller.rb
Labels: CRITICAL, 🐞 Bug

#1934 migrate organization controller spec to request spec
  spec/controllers/organizations_controller_spec.rb
  spec/requests/organization_requests_spec.rb
Labels: hacktoberfest
