Repository rubyforgood/human-essentials, pull requests merged in 2020-12, with the labels that each got.

#1901 Make Dashboard filter sticky, Update Distribution Card and Donation C…
  app/assets/stylesheets/_theme_overrides.scss
  app/assets/stylesheets/application.scss
  app/helpers/items_helper.rb
  app/helpers/organization_helper.rb
  app/helpers/ui_helper.rb
  app/views/dashboard/_dashboard_header.html.erb
  app/views/dashboard/_diaper_drive.html.erb
  app/views/dashboard/_diaper_drive_card.html.erb
  app/views/dashboard/_distribution.html.erb
  app/views/dashboard/_distribution_card.html.erb
  app/views/dashboard/_donation.html.erb
  app/views/dashboard/_donation_card.html.erb
  app/views/dashboard/_manufacturer.html.erb
  app/views/dashboard/_manufacturer_card.html.erb
  app/views/dashboard/_purchase.html.erb
  app/views/dashboard/_purchase_card.html.erb
  app/views/dashboard/index.html.erb
  app/views/layouts/application.html.erb
  app/views/shared/_date_range_picker.html.erb
  spec/system/authorization_system_spec.rb
  spec/system/dashboard_system_spec.rb
  spec/system/donation_system_spec.rb
  spec/system/log_in_system_spec.rb
  spec/system/purchase_system_spec.rb
Labels: ⚡️ Power ⚡️, 💡 Usability

#2047 [2043] Install Knapsack Pro for Parallel Testing
  .github/workflows/rspec.yml
  Gemfile
  Gemfile.lock
  README.md
Labels: WIP

#1838 Include fullstory script to help track & improve UX
  app/helpers/application_helper.rb
  app/views/layouts/application.html.erb
Labels: In Progress
