Repository rubyforgood/human-essentials, pull requests merged in 2021-12, with the labels that each got.

#2635 [WIP] 2630 spec warnings
  app/controllers/adjustments_controller.rb
  app/controllers/audits_controller.rb
  app/controllers/diaper_drive_participants_controller.rb
  app/controllers/diaper_drives_controller.rb
  app/controllers/items_controller.rb
  app/controllers/manufacturers_controller.rb
  app/controllers/vendors_controller.rb
  app/services/kit_create_service.rb
  app/services/partners/request_create_service.rb
  spec/factories/partners.rb
  spec/jobs/notify_partner_job_spec.rb
  spec/rails_helper.rb
  spec/support/provideable_shared_example.rb
  spec/system/audit_system_spec.rb
  spec/system/partner_system_spec.rb
Labels: In Progress, WIP, ruby

#2644 Add libv8-node & nokogiri '-darwin' versions
  Gemfile.lock
Labels: dependencies

#2646 Restore schema version to match contents
  db/schema.rb
Labels: ruby

#2648 Un-skip passing dashboard system example
  spec/system/dashboard_system_spec.rb
Labels: QA, ruby

#2649 [WIP] 2092 annual survey csv
  .gitignore
  app/controllers/reports/annual_reports_controller.rb
  app/controllers/reports/ndbn_annuals_controller.rb
  app/helpers/ui_helper.rb
  app/models/annual_report.rb
  app/models/concerns/issued_at.rb
  app/models/diaper_drive.rb
  app/models/donation.rb
  app/models/item.rb
  app/models/organization.rb
  app/services/exports/export_report_csv_service.rb
  app/services/reports.rb
  app/services/reports/acquisition_report_service.rb
  app/services/reports/adult_incontinence_report_service.rb
  app/services/reports/children_served_report_service.rb
  app/services/reports/other_products_report_service.rb
  app/services/reports/partner_info_report_service.rb
  app/services/reports/summary_info_report_service.rb
  app/services/reports/warehouse_info_report_service.rb
  app/views/layouts/_lte_sidebar.html.erb
  app/views/reports/annual_reports/index.html.erb
  app/views/reports/annual_reports/show.html.erb
  app/views/reports/ndbn_annuals/show.html.erb
  config/routes.rb
  db/migrate/20211224151329_create_annual_reports.rb
  db/schema.rb
  installation.md
  spec/factories/partners.rb
  spec/rails_helper.rb
  spec/requests/reports/annual_reports_requests_spec.rb
  spec/requests/reports/ndbn_requests_spec.rb
  spec/services/exports/export_report_csv_service_spec.rb
  spec/services/reports/acquisition_report_service_spec.rb
  spec/services/reports/adult_incontinence_report_service_spec.rb
  spec/services/reports/children_served_report_service_spec.rb
Labels: Repo First-timer
