Repository rubyforgood/human-essentials, pull requests merged in 2022-02, with the labels that each got.

#2768 Update webpack dev server configs
  babel.config.js
  package.json
  yarn.lock
Labels: javascript

#2743 2676: Reduce dashboard spec date sensitivity, improve descriptions
  .github/workflows/rspec.yml
  spec/support/pages/organization_dashboard_page.rb
  spec/system/dashboard_system_spec.rb
Labels: QA, ruby

#2766 WIP Adding logic to hide form data until user confirms bank creation needs
  app/views/account_requests/new.html.erb
  spec/system/account_request_system_spec.rb
Labels: Repo First-timer

#2784 2762: show $0 on dashboard
  app/helpers/items_helper.rb
  app/views/dashboard/index.html.erb
Labels: ruby
