Repository rubyforgood/human-essentials, pull requests merged in 2022-01, with the labels that each got.

#2698 Update the Installation Guide and link to it from Contributing
  CONTRIBUTING.md
  installation.md
Labels: Repo First-timer

#2682 Temporary workaround for "this month" dashboard example failures in January
  spec/system/dashboard_system_spec.rb
Labels: QA, 🔧 Tech Debt, ruby

#2657 Convert Dashboard spec to use Page Object pattern
  app/views/dashboard/_diaper_drive.html.erb
  app/views/dashboard/_distribution.html.erb
  app/views/dashboard/_donation.html.erb
  app/views/dashboard/_purchase.html.erb
  app/views/dashboard/index.html.erb
  spec/support/image_parser.rb
  spec/support/pages/organization_dashboard_page.rb
  spec/support/pages/organization_new_distribution_page.rb
  spec/support/pages/organization_new_donation_page.rb
  spec/support/pages/organization_new_purchase_page.rb
  spec/support/pages/organization_page.rb
  spec/support/pages/system_spec_page.rb
  spec/system/dashboard_system_spec.rb
Labels: QA, ruby
